<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Vestige</PackageId>
    <Description>Wide event logging library for .NET — canonical log line pattern.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
