<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Vestige.Sinks.SqlServer</PackageId>
    <Description>SQL Server sink for Vestige wide event logging.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vestige\Vestige.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

</Project>
